name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Download WhatsApp auth credentials
      uses: actions/download-artifact@v4
      with:
        name: whatsapp-auth
        path: auth
      continue-on-error: true

    - name: Install dependencies
      run: |
        npm install -g pm2
        npm install --legacy-peer-deps

    - name: Start application with timeout
      run: |
        echo "📂 AVANT lancement : contenu du dossier auth"
        ls -R auth || echo "Pas de dossier auth trouvé"
        timeout 14520s npm run zokou
        echo "📂 APRÈS exécution : contenu du dossier auth"
        ls -R auth || echo "auth introuvable après lancement"

    - name: Upload WhatsApp auth credentials
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: whatsapp-auth
        path: auth